#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: dc0cl4q7rjane4
#      POSTGRES_USER: hjnnjofgbphcvu
#      POSTGRES_PASSWORD: e1f81945f6c0059dc57532e37d593f12bc5dc8214ec7bff8d768671984df3f30
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  backendportfolio:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#
#volumes:
#  postgres_data:
